networks:
  default:
    ipam:
      config:
        - subnet: 172.10.3.0/24
          gateway: 172.10.3.254

services:
  initvar:
    build: ./dockerfiles/init-var
    networks:
      default:
        ipv4_address: 172.10.3.242
    volumes:
      - .:/app

  initdb:
    build: ./dockerfiles/init-db
    networks:
      default:
        ipv4_address: 172.10.3.241
    volumes:
      - .:/app